version: '3.8'

services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - FIREBASE_SERVICE_ACCOUNT_B64=${FIREBASE_SERVICE_ACCOUNT_B64}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
